-- PYRO HR Analytics — Navigation & Role Detection Measures
Is_CEO_CFO = IF(CALCULATE(COUNTROWS(RLS_SecurityMapping), RLS_SecurityMapping[Email] = USERPRINCIPALNAME(), RLS_SecurityMapping[PBI_Role] = "Role_CEO_CFO") > 0, 1, 0)

Is_HR = IF(CALCULATE(COUNTROWS(RLS_SecurityMapping), RLS_SecurityMapping[Email] = USERPRINCIPALNAME(), RLS_SecurityMapping[PBI_Role] IN {"Role_HR", "Role_CEO_CFO"}) > 0, 1, 0)

Is_Employee = IF(CALCULATE(COUNTROWS(RLS_SecurityMapping), RLS_SecurityMapping[Email] = USERPRINCIPALNAME(), RLS_SecurityMapping[PBI_Role] = "Role_Employee") > 0, 1, 0)

Can_See_HR_Page = IF(CALCULATE(COUNTROWS(RLS_SecurityMapping), RLS_SecurityMapping[Email] = USERPRINCIPALNAME(), RLS_SecurityMapping[PBI_Role] IN {"Role_HR", "Role_CEO_CFO"}) > 0, 1, 0)

Can_See_CEO_Page = IF(CALCULATE(COUNTROWS(RLS_SecurityMapping), RLS_SecurityMapping[Email] = USERPRINCIPALNAME(), RLS_SecurityMapping[PBI_Role] = "Role_CEO_CFO") > 0, 1, 0)


